spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: postgres
  flyway:
    default-schema: postgres
    fail-on-missing-locations: true
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
  graphql:
    graphiql:
      enabled: true
