insert into organization (id, name)
values (1, 'The Best Software Inc'),
       (2, 'The Hardware Solutions'),
       (3, 'The John & Partners'),
       (4, 'The Law Offices'),
       (5, 'The Accounting Firm'),
       (6, 'The Marketing Agency'),
       (7, 'The Design Studio'),
       (8, 'The Construction Company'),
       (9, 'The Consulting Group'),
       (10, 'The Medical Center'),
       (11, 'The University'),
       (12, 'The School District'),
       (13, 'The Hospital'),
       (14, 'The Bank'),
       (15, 'The Insurance Company'),
       (16, 'The Retail Store'),
       (17, 'The Restaurant'),
       (18, 'The Hotel'),
       (19, 'The Travel Agency'),
       (20, 'The Real Estate Agency');


-- Reset sequence to the highest id value of organization table because of manual insertions
SELECT setval('organization_id_seq',
              (select max(id) from organization),
              true
       );


insert into employee (email, name, organization_id)
values ('alice@email.com', 'Alice', 1),
       ('bob@email.com', 'Bob', 1),
       ('charles@email.com', 'Charles', 1),
       ('duke@email.com', 'Duke', 1),
       ('emma@email.com', 'Emma', 1),
       ('frank@email.com', 'Frank', 1),
       ('grace@email.com', 'Grace', 1),
       ('henry@email.com', 'Henry', 1),
       ('isabel@email.com', 'Isabel', 1),
       ('jack@email.com', 'Jack', 1),
       ('kate@email.com', 'Kate', 1),
       ('leo@email.com', 'Leo', 1),
       ('mia@email.com', 'Mia', 1),
       ('nathan@email.com', 'Nathan', 1),
       ('olivia@email.com', 'Olivia', 1),
       ('peter@email.com', 'Peter', 1),
       ('quinn@email.com', 'Quinn', 1),
       ('rachel@email.com', 'Rachel', 1),
       ('sam@email.com', 'Sam', 1),
       ('tina@email.com', 'Tina', 1),
       ('ursula@email.com', 'Ursula', 2),
       ('vince@email.com', 'Vince', 2),
       ('william@email.com', 'William', 2),
       ('xena@email.com', 'Xena', 2),
       ('yasmine@email.com', 'Yasmine', 2),
       ('zeke@email.com', 'Zeke', 2),
       ('albert@email.com', 'Albert', 2),
       ('bella@email.com', 'Bella', 2),
       ('carl@email.com', 'Carl', 2),
       ('diana@email.com', 'Diana', 2),
       ('edward@email.com', 'Edward', 2),
       ('fiona@email.com', 'Fiona', 2),
       ('george@email.com', 'George', 2),
       ('hannah@email.com', 'Hannah', 2),
       ('zoe@email.com', 'Zoe', 2);
